# Tensor Flow Basics

### Author: Olufemi Victor
##### Team: Project team Pluto: Basics to Computer Vision with Tensorflow.
##### Week 1

The projects with team pluto all require tensorflow 2.0 and above,one of the many interesting features about tensorflow 2.0+ is that it has Default Eager Execution unlike previous versions of tensorflow. Eager execution simply tells the interpreter to run the code line by line rather than run codes in sesions.

let's get to it!, first we import tensorflow and confirm the version we are currently running.

In [4]:
import tensorflow as tf
tf.__version__

'2.1.0'

As you can see, i am running the tensorflow 2+ version, this means eager execution is enabled automatically, let me confirm this if true, tf.executing_eagerly() returns boolean

In [5]:
tf.executing_eagerly()

True

Next, we create constant tensors and perform simple operations on them. In this short example, i create a tensor with four rows and two columns.On printing the tensor, we see clearly how that it shows the shape and data ty

In [13]:
t1 = tf.constant([[7, 8],[9, 10],[11, 12],[13, 14]])
print(t1)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]], shape=(4, 2), dtype=int32)


Let's create another one with the same shape.

In [14]:
t2 = tf.constant([[2,4],[2,5],[2,6],[2,7]])
print(t2)

tf.Tensor(
[[2 4]
 [2 5]
 [2 6]
 [2 7]], shape=(4, 2), dtype=int32)


Concatenating two tensors: Tensors can be concatenated with respect to their rows or column.

In [21]:
tconcat = tf.concat(values = [t1,t2], axis = 0)
print("This concatenation has increased the number of rows. See new shape")
print(tconcat)

This concatenation has increased the number of rows. See new shape
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [14 32]
 [18 50]
 [22 72]
 [26 98]], shape=(8, 2), dtype=int32)


In [22]:
tconcat = tf.concat(values = [t1,t2], axis = 1)
print("This concatenation has increased the number of rows. See new shape")
print(tconcat)

This concatenation has increased the number of rows. See new shape
tf.Tensor(
[[ 7  8 14 32]
 [ 9 10 18 50]
 [11 12 22 72]
 [13 14 26 98]], shape=(4, 4), dtype=int32)


Create tensors of just zeros, just by describing the shape

In [25]:
tzeros = tf.zeros(shape = [4,5], dtype = tf.int32)
print(tzeros)

tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(4, 5), dtype=int32)


Create tensors full of ones

In [26]:
tzeros = tf.ones(shape = [4,5], dtype = tf.int32)
print(tzeros)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


Reshaping your Tensor. See how we can reshape a tensor, but you must keep in mind that the number of values must be equal. The first one has a shape(4,4), that is 16 values, the reshaped one has a shape(a,b) such that (a x b) must be 16 too.

In [36]:
print("Tensor before reshaping\n")
print(tconcat,"\n")
t_reshaped = tf.reshape(tensor = tconcat, shape = [8,2])
print(t_reshaped)

Tensor before reshaping

tf.Tensor(
[[ 7  8 14 32]
 [ 9 10 18 50]
 [11 12 22 72]
 [13 14 26 98]], shape=(4, 4), dtype=int32) 

tf.Tensor(
[[ 7  8]
 [14 32]
 [ 9 10]
 [18 50]
 [11 12]
 [22 72]
 [13 14]
 [26 98]], shape=(8, 2), dtype=int32)


You can also reshape into a 3 dimensional matrix, provided the number of values in the new shape multiply to 16

In [39]:
print("Tensor before reshaping\n")
print(tconcat,"\n")
t_reshaped = tf.reshape(tensor = tconcat, shape = [2,2,4])
print("see 3D tensor.....\n")
print(t_reshaped)

Tensor before reshaping

tf.Tensor(
[[ 7  8 14 32]
 [ 9 10 18 50]
 [11 12 22 72]
 [13 14 26 98]], shape=(4, 4), dtype=int32) 

see 3D tensor.....

tf.Tensor(
[[[ 7  8 14 32]
  [ 9 10 18 50]]

 [[11 12 22 72]
  [13 14 26 98]]], shape=(2, 2, 4), dtype=int32)


Convert content's datatype from float to integer and vice versa using tf.cast()

In [48]:
t3 = tf.constant([[2.1,3.3,4.6],[4.3,5.2,6.1],[7.2,8.4,9.0]])
print(t3)
print("\nsee values now formatted as integers")
print(tf.cast(t3, tf.int32))

tf.Tensor(
[[2.1 3.3 4.6]
 [4.3 5.2 6.1]
 [7.2 8.4 9. ]], shape=(3, 3), dtype=float32)

see values now formatted as integers
tf.Tensor(
[[2 3 4]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [50]:
t3 = tf.constant([[2,3,4],[4,5,6],[7,8,9]])
print(t3)
print("\nsee values now formatted as float")
print(tf.cast(t3, tf.float32))

tf.Tensor(
[[2 3 4]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

see values now formatted as float
tf.Tensor(
[[2. 3. 4.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


###### SIMPLE ALGEBRAIC OPERATIONS

###### Transpose

Transpose: the matrix transpose function can easily be done using tf.transpose()

In [73]:
t4 = tf.constant([[2,3,4,5,6,7],[7,6,5,4,3,2],[2,3,4,5,6,7]])
print(t4)

print("\n let's transpose this matrix")
print(tf.transpose(t4))

tf.Tensor(
[[2 3 4 5 6 7]
 [7 6 5 4 3 2]
 [2 3 4 5 6 7]], shape=(3, 6), dtype=int32)

 let's transpose this matrix
tf.Tensor(
[[2 7 2]
 [3 6 3]
 [4 5 4]
 [5 4 5]
 [6 3 6]
 [7 2 7]], shape=(6, 3), dtype=int32)


###### Multiplication

Multiplication: As the rule is for any matrix multiplication, the number of rows of A must be equal to the number of column in B for matrix multiplication of A and B.

I'll cheat here by just using t4 and t4's transpose, this satisfies the rule.

In [63]:
print("see matrix A",t4)
t5 = tf.transpose(t4)
print("see matrix B\n", t5)
t6 = tf.matmul(t5,t4)
print("\n see matrix multiplication", t6)

see matrix A tf.Tensor(
[[2 3 4 5 6 7]
 [7 6 5 4 3 2]
 [2 3 4 5 6 7]], shape=(3, 6), dtype=int32)
see matrix B
 tf.Tensor(
[[2 7 2]
 [3 6 3]
 [4 5 4]
 [5 4 5]
 [6 3 6]
 [7 2 7]], shape=(6, 3), dtype=int32)

 see matrix multiplication tf.Tensor(
[[ 57  54  51  48  45  42]
 [ 54  54  54  54  54  54]
 [ 51  54  57  60  63  66]
 [ 48  54  60  66  72  78]
 [ 45  54  63  72  81  90]
 [ 42  54  66  78  90 102]], shape=(6, 6), dtype=int32)


Element wise Multiplication: For element wise multiplication, the two tensors must have equal number of rows and column, unless one of the matrix has a single row or column.

In [69]:
t7 = tf.constant([[1,3,5,6],[7,9,11,12]])
t8 = tf.constant([[2,2,2,1],[2,2,2,1]])
tmultiplied = tf.multiply(t7,t8)
print(tmultiplied)

tf.Tensor(
[[ 2  6 10  6]
 [14 18 22 12]], shape=(2, 4), dtype=int32)


###### To Numpy

There is a lot of flexibility between tensors and numpy arrays, tensorflow's tensors could be easily converted to arrays. Let's see examples.

In [88]:
print("Tensor\n", t1)
print("\nAs numpy array\n",t1.numpy())

Tensor
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]], shape=(4, 2), dtype=int32)

As numpy array
 [[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


We see how those extra info about shape and dtype are discarded when converted to numpy arrays, quite interesting.

Confirm That t1 is of type tensor.

In [95]:
type(t1)

tensorflow.python.framework.ops.EagerTensor

confirm that the type is now changed to numpy array.

In [96]:
type(t1.numpy())

numpy.ndarray

###### Determinant

To find determinant of matrix, it's quite easy. don't forget rules still apply, So it must be a square matrix, also, the tensor type must be half, float or complex, so we must cast it into these datatype

In [85]:
tmat = tf.constant([[1,2,3,4],[4,3,2,1],[2,4,6,1],[2,2,4,3]])
t9 = tf.cast(tmat, tf.float32)
print("square matrix", t9)

print("\nThis is info about the determinant\n",tf.linalg.det(t9).numpy())

square matrix tf.Tensor(
[[1. 2. 3. 4.]
 [4. 3. 2. 1.]
 [2. 4. 6. 1.]
 [2. 2. 4. 3.]], shape=(4, 4), dtype=float32)

This is info about the determinant
 -69.99999


The End.

Read more from Tensorflow's official docs [here](https://www.tensorflow.org/learn)